### ISSUE TITLE
[PLANNING][FASE 1] - Reunião 01 

### ISSUE THREAD

**Issue by matheusarauj** [computacao-ufcg/alumni-backend#1]
Reunião 01 referente ao planejamento de atividades da primeira fase de desenvolvimento do `pdc-alumni` realizada na data 24/09/2020

### Backend: 
@natalia-sa 

- [ ] Rota pública do serviço alumni `/publicKey` 

### Match LinkedIn: 
@jonatas-lima 

- [ ] Classe Match: método `Collection getMatches(UFCGalumniData alumni, String schoolUrl)` => pegar as informações do parâmetro passado no método em `linkedinAlumnosData` e retorna uma coleção de dados referente ao objeto

### Frontend: 
@ielepassos 

- [ ] Tela de login 

- [ ] Rota `/login` 

@fubica 

- [ ] Gerar credenciais de acesso do usuário no frontend

@matheusarauj 

- [ ] Fabricar as issues referentes às atividades listadas acima

**Comment by fubica** [comment]
A assinatura de getMatches(UFCGalumniData) é, na realidade, a seguinte:

Collection<LinkedinAlumnusData> getMatches(UFCGalumniData alumni, String schoolUrl);
