### ISSUE TITLE
[BACKEND][MATCH] - Alumni URL's

### ISSUE THREAD

**Issue by ielepassos** [computacao-ufcg/alumni-backend#28]
A rota **/match PUT** passa para o front-end uma URL no parâmetro 'LinkedinID',  contudo, não é possível colocar uma URL dentro de outra URL.

**Comment by jonatas-lima** [comment]
Acho que o problema foi resolvido, baixa a minha branch e vê se resolve.

**Comment by fubica** [comment]
Done
