### ISSUE TITLE
Criar a rota /match/search

### ISSUE THREAD

**Issue by jonatas-lima** [computacao-ufcg/alumni-backend#41]
Essa rota recebe nos query params o nome a ser buscado na coleção de matches já consolidados (obs: devem ser buscados todos os nomes que batem com o nome da query. isto é, se o name=maria devem ser buscados todos os matches cujo nome possui maria)

**Comment by fubica** [comment]
Além do query param name, tem também os query params admission e graduation. Todos os query params são expressões regulares. Ou seja, posso passar algo como name=Mar* ou admission=20??.1.
