### ISSUE TITLE
Criar rota /alumniSiteStatistics

### ISSUE THREAD

**Issue by natalia-sa** [computacao-ufcg/alumni-backend#47]
Criar  a rota /alumniSiteStatistics, do tipo get, que trará dados a serem exibidos no alumi site. A princípio os dados a serem retornados são:
- Número de alunos já cadastrados
- Número de alunos formados no último ano
- Número de alunos empregados por cada tipo de employer
- Quantos anos o curso de Ciência da Computação possui.

**Comment by paulojuniore** [comment]
Closed by #50 PR.
